export const PublicApiErrorCodes = Object.freeze({
    API_UNAVAILABLE: 'YUZI_PHONE_API_UNAVAILABLE',
    CAPABILITY_NOT_AVAILABLE: 'YUZI_PHONE_CAPABILITY_NOT_AVAILABLE',
    API_NOT_IMPLEMENTED: 'YUZI_PHONE_API_NOT_IMPLEMENTED',
    INVALID_ARGUMENT: 'YUZI_PHONE_API_INVALID_ARGUMENT',
    ALREADY_REGISTERED: 'YUZI_PHONE_API_ALREADY_REGISTERED',
    NOT_FOUND: 'YUZI_PHONE_API_NOT_FOUND',
    MESSAGE_SCOPE_MISMATCH: 'YUZI_MESSAGE_SCOPE_MISMATCH',
    MESSAGE_CONVERSATION_NOT_FOUND: 'YUZI_MESSAGE_CONVERSATION_NOT_FOUND',
});
